### ISSUE TITLE
Add Will to project

### ISSUE THREAD

**Issue by NetScr1be** [NetScr1be/Lubuntu32Bit#3]
Source: [GitHub Add Collaborator](https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/managing-access-to-your-user-accounts-project-boards#:~:text=Inviting%20collaborators%20to%20a%20user%2Downed%20project%20board,-Navigate%20to%20the&text=Click%20%2C%20then%20click%20Settings.,username%20and%20click%20Add%20collaborator.)

1. Navigate to the project board where you want to add an collaborator
2. On the top-right side of the project board, click  Menu
3. Click , then click Settings
4. In the left sidebar, click Collaborators
5. Under "Search by username, full name or email address", type the collaborator's name, username, or GitHub email
6. In the search results, click the correct username and click Add collaborator
7. The new collaborator has read permissions by default
8. Optionally, next to the new collaborator's name, use the drop-down
8. Menu and choose a different permission level.

**Comment by NetScr1be** [comment]
Done.

Waiting for Will to confirm by closing this issue.

**Comment by Will-Flow** [comment]
Understood

**Comment by Will-Flow** [comment]
test

**Comment by Will-Flow** [comment]
test1

**Comment by Will-Flow** [comment]
works
